INSERT INTO USERS VALUES (DEFAULT ,'test', 'test',FALSE );
INSERT INTO USERS VALUES(DEFAULT, 'test1', 'test1',FALSE);
INSERT INTO USERS VALUES(DEFAULT, 'vlad', 'vlad',FALSE);

INSERT INTO authorities VALUES ('test',DEFAULT );
INSERT INTO authorities VALUES('test1',DEFAULT );
INSERT INTO authorities VALUES('vlad',DEFAULT );